//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UVtools.GUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color PreviousNextLayerColor {
            get {
                return ((global::System.Drawing.Color)(this["PreviousNextLayerColor"]));
            }
            set {
                this["PreviousNextLayerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color IslandColor {
            get {
                return ((global::System.Drawing.Color)(this["IslandColor"]));
            }
            set {
                this["IslandColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color IslandHLColor {
            get {
                return ((global::System.Drawing.Color)(this["IslandHLColor"]));
            }
            set {
                this["IslandHLColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SandyBrown")]
        public global::System.Drawing.Color ResinTrapColor {
            get {
                return ((global::System.Drawing.Color)(this["ResinTrapColor"]));
            }
            set {
                this["ResinTrapColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color ResinTrapHLColor {
            get {
                return ((global::System.Drawing.Color)(this["ResinTrapHLColor"]));
            }
            set {
                this["ResinTrapHLColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color TouchingBoundsColor {
            get {
                return ((global::System.Drawing.Color)(this["TouchingBoundsColor"]));
            }
            set {
                this["TouchingBoundsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Magenta")]
        public global::System.Drawing.Color PreviousLayerColor {
            get {
                return ((global::System.Drawing.Color)(this["PreviousLayerColor"]));
            }
            set {
                this["PreviousLayerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::System.Drawing.Color NextLayerColor {
            get {
                return ((global::System.Drawing.Color)(this["NextLayerColor"]));
            }
            set {
                this["NextLayerColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeSettings {
            get {
                return ((bool)(this["UpgradeSettings"]));
            }
            set {
                this["UpgradeSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartMaximized {
            get {
                return ((bool)(this["StartMaximized"]));
            }
            set {
                this["StartMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForUpdatesOnStartup {
            get {
                return ((bool)(this["CheckForUpdatesOnStartup"]));
            }
            set {
                this["CheckForUpdatesOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LayerAutoRotateBestView {
            get {
                return ((bool)(this["LayerAutoRotateBestView"]));
            }
            set {
                this["LayerAutoRotateBestView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LayerDifferenceDefault {
            get {
                return ((bool)(this["LayerDifferenceDefault"]));
            }
            set {
                this["LayerDifferenceDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ComputeIssuesOnLoad {
            get {
                return ((bool)(this["ComputeIssuesOnLoad"]));
            }
            set {
                this["ComputeIssuesOnLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LayerZoomToFit {
            get {
                return ((bool)(this["LayerZoomToFit"]));
            }
            set {
                this["LayerZoomToFit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ComputeIslands {
            get {
                return ((bool)(this["ComputeIslands"]));
            }
            set {
                this["ComputeIslands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ComputeResinTraps {
            get {
                return ((bool)(this["ComputeResinTraps"]));
            }
            set {
                this["ComputeResinTraps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte IslandRequiredAreaToProcessCheck {
            get {
                return ((byte)(this["IslandRequiredAreaToProcessCheck"]));
            }
            set {
                this["IslandRequiredAreaToProcessCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte IslandRequiredPixelBrightnessToProcessCheck {
            get {
                return ((byte)(this["IslandRequiredPixelBrightnessToProcessCheck"]));
            }
            set {
                this["IslandRequiredPixelBrightnessToProcessCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte IslandRequiredPixelsToSupport {
            get {
                return ((byte)(this["IslandRequiredPixelsToSupport"]));
            }
            set {
                this["IslandRequiredPixelsToSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public byte IslandRequiredPixelBrightnessToSupport {
            get {
                return ((byte)(this["IslandRequiredPixelBrightnessToSupport"]));
            }
            set {
                this["IslandRequiredPixelBrightnessToSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public byte ResinTrapRequiredAreaToProcessCheck {
            get {
                return ((byte)(this["ResinTrapRequiredAreaToProcessCheck"]));
            }
            set {
                this["ResinTrapRequiredAreaToProcessCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte ResinTrapRequiredBlackPixelsToDrain {
            get {
                return ((byte)(this["ResinTrapRequiredBlackPixelsToDrain"]));
            }
            set {
                this["ResinTrapRequiredBlackPixelsToDrain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public byte ResinTrapMaximumPixelBrightnessToDrain {
            get {
                return ((byte)(this["ResinTrapMaximumPixelBrightnessToDrain"]));
            }
            set {
                this["ResinTrapMaximumPixelBrightnessToDrain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoComputeIssuesClickOnTab {
            get {
                return ((bool)(this["AutoComputeIssuesClickOnTab"]));
            }
            set {
                this["AutoComputeIssuesClickOnTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color OutlinePrintVolumeBoundsColor {
            get {
                return ((global::System.Drawing.Color)(this["OutlinePrintVolumeBoundsColor"]));
            }
            set {
                this["OutlinePrintVolumeBoundsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte OutlinePrintVolumeBoundsLineThickness {
            get {
                return ((byte)(this["OutlinePrintVolumeBoundsLineThickness"]));
            }
            set {
                this["OutlinePrintVolumeBoundsLineThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color OutlineLayerBoundsColor {
            get {
                return ((global::System.Drawing.Color)(this["OutlineLayerBoundsColor"]));
            }
            set {
                this["OutlineLayerBoundsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte OutlineLayerBoundsLineThickness {
            get {
                return ((byte)(this["OutlineLayerBoundsLineThickness"]));
            }
            set {
                this["OutlineLayerBoundsLineThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color OutlineHollowAreasColor {
            get {
                return ((global::System.Drawing.Color)(this["OutlineHollowAreasColor"]));
            }
            set {
                this["OutlineHollowAreasColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public sbyte OutlineHollowAreasLineThickness {
            get {
                return ((sbyte)(this["OutlineHollowAreasLineThickness"]));
            }
            set {
                this["OutlineHollowAreasLineThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OutlinePrintVolumeBounds {
            get {
                return ((bool)(this["OutlinePrintVolumeBounds"]));
            }
            set {
                this["OutlinePrintVolumeBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutlineLayerBounds {
            get {
                return ((bool)(this["OutlineLayerBounds"]));
            }
            set {
                this["OutlineLayerBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutlineHollowAreas {
            get {
                return ((bool)(this["OutlineHollowAreas"]));
            }
            set {
                this["OutlineHollowAreas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ZoomToFitPrintVolumeBounds {
            get {
                return ((bool)(this["ZoomToFitPrintVolumeBounds"]));
            }
            set {
                this["ZoomToFitPrintVolumeBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127")]
        public byte ResinTrapBinaryThreshold {
            get {
                return ((byte)(this["ResinTrapBinaryThreshold"]));
            }
            set {
                this["ResinTrapBinaryThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte IslandBinaryThreshold {
            get {
                return ((byte)(this["IslandBinaryThreshold"]));
            }
            set {
                this["IslandBinaryThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte DefaultOpenFileExtension {
            get {
                return ((byte)(this["DefaultOpenFileExtension"]));
            }
            set {
                this["DefaultOpenFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte CrosshairFadeLevel {
            get {
                return ((byte)(this["CrosshairFadeLevel"]));
            }
            set {
                this["CrosshairFadeLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public byte ZoomLockLevel {
            get {
                return ((byte)(this["ZoomLockLevel"]));
            }
            set {
                this["ZoomLockLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGreen")]
        public global::System.Drawing.Color PixelEditorAddPixelColor {
            get {
                return ((global::System.Drawing.Color)(this["PixelEditorAddPixelColor"]));
            }
            set {
                this["PixelEditorAddPixelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color PixelEditorAddPixelHLColor {
            get {
                return ((global::System.Drawing.Color)(this["PixelEditorAddPixelHLColor"]));
            }
            set {
                this["PixelEditorAddPixelHLColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaleVioletRed")]
        public global::System.Drawing.Color PixelEditorRemovePixelColor {
            get {
                return ((global::System.Drawing.Color)(this["PixelEditorRemovePixelColor"]));
            }
            set {
                this["PixelEditorRemovePixelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color PixelEditorRemovePixelHLColor {
            get {
                return ((global::System.Drawing.Color)(this["PixelEditorRemovePixelHLColor"]));
            }
            set {
                this["PixelEditorRemovePixelHLColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::System.Drawing.Color PixelEditorSupportColor {
            get {
                return ((global::System.Drawing.Color)(this["PixelEditorSupportColor"]));
            }
            set {
                this["PixelEditorSupportColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Plum")]
        public global::System.Drawing.Color PixelEditorDrainHoleColor {
            get {
                return ((global::System.Drawing.Color)(this["PixelEditorDrainHoleColor"]));
            }
            set {
                this["PixelEditorDrainHoleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkCyan")]
        public global::System.Drawing.Color PixelEditorSupportHLColor {
            get {
                return ((global::System.Drawing.Color)(this["PixelEditorSupportHLColor"]));
            }
            set {
                this["PixelEditorSupportHLColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purple")]
        public global::System.Drawing.Color PixelEditorDrainHoleHLColor {
            get {
                return ((global::System.Drawing.Color)(this["PixelEditorDrainHoleHLColor"]));
            }
            set {
                this["PixelEditorDrainHoleHLColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileSaveNamePreffix {
            get {
                return ((string)(this["FileSaveNamePreffix"]));
            }
            set {
                this["FileSaveNamePreffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_copy")]
        public string FileSaveNameSuffix {
            get {
                return ((string)(this["FileSaveNameSuffix"]));
            }
            set {
                this["FileSaveNameSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileSavePromptOverwrite {
            get {
                return ((bool)(this["FileSavePromptOverwrite"]));
            }
            set {
                this["FileSavePromptOverwrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileOpenDefaultDirectory {
            get {
                return ((string)(this["FileOpenDefaultDirectory"]));
            }
            set {
                this["FileOpenDefaultDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileSaveDefaultDirectory {
            get {
                return ((string)(this["FileSaveDefaultDirectory"]));
            }
            set {
                this["FileSaveDefaultDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileConvertDefaultDirectory {
            get {
                return ((string)(this["FileConvertDefaultDirectory"]));
            }
            set {
                this["FileConvertDefaultDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileExtractDefaultDirectory {
            get {
                return ((string)(this["FileExtractDefaultDirectory"]));
            }
            set {
                this["FileExtractDefaultDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ZoomIssues {
            get {
                return ((bool)(this["ZoomIssues"]));
            }
            set {
                this["ZoomIssues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte LayerRepairDefaultClosingIterations {
            get {
                return ((byte)(this["LayerRepairDefaultClosingIterations"]));
            }
            set {
                this["LayerRepairDefaultClosingIterations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte LayerRepairDefaultOpeningIterations {
            get {
                return ((byte)(this["LayerRepairDefaultOpeningIterations"]));
            }
            set {
                this["LayerRepairDefaultOpeningIterations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LayerRepairLayersIslands {
            get {
                return ((bool)(this["LayerRepairLayersIslands"]));
            }
            set {
                this["LayerRepairLayersIslands"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LayerRepairResinTraps {
            get {
                return ((bool)(this["LayerRepairResinTraps"]));
            }
            set {
                this["LayerRepairResinTraps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LayerRepairRemoveEmptyLayers {
            get {
                return ((bool)(this["LayerRepairRemoveEmptyLayers"]));
            }
            set {
                this["LayerRepairRemoveEmptyLayers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte LayerRepairRemoveIslandsBelowEqualPixelsDefault {
            get {
                return ((byte)(this["LayerRepairRemoveIslandsBelowEqualPixelsDefault"]));
            }
            set {
                this["LayerRepairRemoveIslandsBelowEqualPixelsDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PartialUpdateIslandsOnEditing {
            get {
                return ((bool)(this["PartialUpdateIslandsOnEditing"]));
            }
            set {
                this["PartialUpdateIslandsOnEditing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloseEditOnApply {
            get {
                return ((bool)(this["CloseEditOnApply"]));
            }
            set {
                this["CloseEditOnApply"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IslandAllowDiagonalBonds {
            get {
                return ((bool)(this["IslandAllowDiagonalBonds"]));
            }
            set {
                this["IslandAllowDiagonalBonds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public uint CrosshairLineLength {
            get {
                return ((uint)(this["CrosshairLineLength"]));
            }
            set {
                this["CrosshairLineLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CrosshairShowOnlyOnSelectedIssues {
            get {
                return ((bool)(this["CrosshairShowOnlyOnSelectedIssues"]));
            }
            set {
                this["CrosshairShowOnlyOnSelectedIssues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte CrosshairLineMargin {
            get {
                return ((byte)(this["CrosshairLineMargin"]));
            }
            set {
                this["CrosshairLineMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color CrosshairColor {
            get {
                return ((global::System.Drawing.Color)(this["CrosshairColor"]));
            }
            set {
                this["CrosshairColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ComputeTouchingBounds {
            get {
                return ((bool)(this["ComputeTouchingBounds"]));
            }
            set {
                this["ComputeTouchingBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ComputeEmptyLayers {
            get {
                return ((bool)(this["ComputeEmptyLayers"]));
            }
            set {
                this["ComputeEmptyLayers"] = value;
            }
        }
    }
}
